### ISSUE TITLE
Way to "Enter VR" in the build?

### ISSUE THREAD

**Issue by dsarno** [chrmi/unity-webvr#1]
Hi Chris,

Can't tell if you're still maintaining this project, but my question was about being able to "Enter VR" in the sample app.  I get it running fine through Firefox, but it seems like it won't display the content in the Rift HMD until it goes into "VR" mode somehow, and I don't see a way to do this.  Other apps have a button to press to "Enter VR Mode" (like this - https://webvr.info/samples/03-vr-presentation.html).  

Any suggestions?  Thanks.

**Comment by chrmi** [comment]
I had to re-write a lot of this to work with Unity 5.6, which made a lot of breaking changes to WebGL export regarding communication between the two layers.  As of now this version only supports the communication path to the WebVR Polyfill.

A few things that might be of interested if you wanted to dive in further:

https://github.com/googlevr/webvr-polyfill/blob/master/examples/basic/index.html#L176

https://github.com/chrmi/unity-webvr/blob/master/Assets/Plugins/WebGL/webvr.jslib#L4
https://github.com/chrmi/unity-webvr/blob/master/Assets/Scripts/WebVRCamera.cs#L7

https://github.com/gtk2k/Unity-WebVR-Assets/blob/master/WebVRAssets/StereoCamera.cs
