### ISSUE TITLE
Can't get this project (or any polyfill demos) working on Vive/Rift

### ISSUE THREAD

**Issue by apalma23** [chrmi/unity-webvr#2]
Hey Chris!

I wrote part of the original Unity WebVR export with Mozilla's help last year:
 [hacks.mozilla.org/2016/05/exporting-an-indie-unity-game-to-webvr/](url)

Since then though, the Unity export template has changed, and more importantly, Polyfill enables WebVR support in current mainstream browsers. Unfortunately, I can't get Polyfill examples working in my Vive or my Rift out of Unity 2017.1, testing in Chrome 59, Brandon's Chromium, OR Firefox Nightly.

Apologies for listing as an issue if it's just me - didn't have any other way to contact you! You can email me if you want at anthony[at]playonjump[dot]com if that's easier.

**Comment by chrmi** [comment]
Hi @apalma23 -- we connected on Slack, sounds like we need to add stereo camera back into this (i.e. https://github.com/gtk2k/Unity-WebVR-Assets/blob/master/WebVRAssets/StereoCamera.cs) -- feel free to submit a PR if you end up getting that working (as well as the other enhancements you mentioned, though I would compartmentalize those as optional add-ins based on platform type).

**Comment by apalma23** [comment]
Haha yes, glad I finally got a hold of you! Obviously worked through the problem above (mostly a misunderstanding of what polyfill did). With FF55 rolling out WebVR1.1, this is a non-issue, so feel free to close it.

I'll keep you posted on my progress otherwise and can make a PR in the future, although I won't have time to break it up anytime soon as you suggest unfortunately.

Thanks again for the help!

**Comment by chrmi** [comment]
Cool, good luck :)
