### ISSUE TITLE
EntryPointNotFoundException: FinishLoading

### ISSUE THREAD

**Issue by bradley-newman** [chrmi/unity-webvr#3]
I get the following error on start when running the "WebVR" sample scene in Unity 5.6.1f1 64bit editor. Is it not meant to work in the editor?

```
EntryPointNotFoundException: FinishLoading
WebVRCamera.Start () (at Assets/Scripts/WebVRCamera.cs:42)
```

**Comment by chrmi** [comment]
@bradley-newman Sorry for a very late response, I haven't been focusing on this repo.

Are you still having this issue?  If so, and you're still wanting to get it running, have you tried running the latest Unity 2017?

I just started breaking the idea of "Unity WebVR" into possibly a couple different repos -- one for WebGL, one for WebVR Polyfill integration, and one for the VR Camera and tools needed to actually achieve VR in browser -- but it will be some time before any of that is helpful to anyone.

Let me know if you're still having trouble on 2017 and would like to debug it further.

**Comment by AhambaliJ** [comment]
Hello, I'm currently facing this issue as well. I am currently running on Unity 2017.2.1f1. Would be very helpful if you could help in debugging this issue.

**Comment by chrmi** [comment]
Mozilla is maintaining this now: https://github.com/mozilla/unity-webvr-export
